services:

  golang:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    extra_hosts:
      - "host.docker.internal:host-gateway"

  golang-mysql:
    image: mysql:8.0.30-debian
    #container_name: test-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_password
    # ports:
    #   - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d


# C:\Windows\system32\drivers\etc\hosts (bloco de notas em modo administrador)

# 127.0.0.1 host.docker.internal

## Linux ou Mac (Docker Desktop)

# /etc/hosts

# 127.0.0.1 host.docker.internal

# host.docker.internal:8000/partner1
# host.docker.internal:8000/partner2